/* data-words.js — thèmes, mots et caractères. */
const THEMES=[
  {id:'presenter',      n:'Se présenter'},
  {id:'decrire',        n:'Présenter et décrire quelqu\u2019un'},
  {id:'famille',        n:'La famille'},
  {id:'quotidien',      n:'Loisirs, habitudes, quotidien'},
  {id:'nourriture',     n:'La nourriture et le restaurant'},
  {id:'achats',         n:'Faire des achats'},
  {id:'temps',          n:'Se repérer dans le temps'},
  {id:'passe',          n:'Raconter au passé'},
  {id:'espace',         n:'Se repérer dans l\u2019espace'},
  {id:'logement',       n:'Le logement'},
  {id:'travail',        n:'Le travail et les études'},
  {id:'voyage',         n:'Le voyage'},
  {id:'sante',          n:'La santé'},
  {id:'projets',        n:'Parler de ses projets'},
  {id:'avis',           n:'Donner son avis, comparer'}
];

const WORDS=[
  // ---- HSK 2 · se présenter
  {id:'w201',hz:'名字',py:'míng zi',fr:'prénom, nom',hsk:2,th:['presenter']},
  {id:'w202',hz:'叫',py:'jiào',fr:'s\u2019appeler',hsk:2,th:['presenter']},
  {id:'w203',hz:'姓',py:'xìng',fr:'nom de famille ; s\u2019appeler (de famille)',hsk:2,th:['presenter']},
  {id:'w204',hz:'认识',py:'rèn shi',fr:'connaître, faire la connaissance de',hsk:2,th:['presenter','decrire']},
  {id:'w205',hz:'高兴',py:'gāo xìng',fr:'content, heureux',hsk:2,th:['presenter']},
  {id:'w206',hz:'岁',py:'suì',fr:'an(s) — âge',hsk:2,th:['presenter']},
  {id:'w207',hz:'住',py:'zhù',fr:'habiter',hsk:2,th:['presenter','logement']},
  {id:'w208',hz:'工作',py:'gōng zuò',fr:'travail ; travailler',hsk:2,th:['presenter','travail']},
  {id:'w209',hz:'学生',py:'xué sheng',fr:'élève, étudiant',hsk:2,th:['presenter','travail']},
  {id:'w210',hz:'老师',py:'lǎo shī',fr:'professeur',hsk:2,th:['presenter','travail']},
  {id:'w211',hz:'医生',py:'yī shēng',fr:'médecin',hsk:2,th:['presenter','travail','sante']},
  {id:'w212',hz:'朋友',py:'péng you',fr:'ami',hsk:2,th:['presenter','famille']},
  {id:'w213',hz:'中国',py:'Zhōng guó',fr:'la Chine',hsk:2,th:['presenter']},
  {id:'w214',hz:'汉语',py:'Hàn yǔ',fr:'le chinois (langue)',hsk:2,th:['presenter']},
  {id:'w215',hz:'哪',py:'nǎ',fr:'quel, lequel',hsk:2,th:['presenter']},
  {id:'w216',hz:'多大',py:'duō dà',fr:'quel âge',hsk:2,th:['presenter']},
  {id:'w217',hz:'会',py:'huì',fr:'savoir (faire), pouvoir',hsk:2,th:['presenter']},
  {id:'w218',hz:'说',py:'shuō',fr:'dire, parler',hsk:2,th:['presenter']},

  // ---- HSK 3 · se présenter
  {id:'w301',hz:'介绍',py:'jiè shào',fr:'présenter (quelqu\u2019un)',hsk:3,th:['presenter','decrire']},
  {id:'w302',hz:'自己',py:'zì jǐ',fr:'soi-même',hsk:3,th:['presenter']},
  {id:'w303',hz:'国家',py:'guó jiā',fr:'pays',hsk:3,th:['presenter','voyage']},
  {id:'w304',hz:'城市',py:'chéng shì',fr:'ville',hsk:3,th:['presenter','espace']},
  {id:'w305',hz:'结婚',py:'jié hūn',fr:'se marier',hsk:3,th:['presenter','famille']},
  {id:'w306',hz:'同事',py:'tóng shì',fr:'collègue',hsk:3,th:['presenter','travail']},
  {id:'w307',hz:'邻居',py:'lín jū',fr:'voisin',hsk:3,th:['presenter','logement']},
  {id:'w308',hz:'经理',py:'jīng lǐ',fr:'directeur, responsable',hsk:3,th:['presenter','travail']},
  {id:'w309',hz:'护士',py:'hù shi',fr:'infirmier, infirmière',hsk:3,th:['presenter','travail','sante']},
  {id:'w310',hz:'留学生',py:'liú xué shēng',fr:'étudiant étranger',hsk:3,th:['presenter','travail']},
  {id:'w311',hz:'爱好',py:'ài hào',fr:'passe-temps, centre d\u2019intérêt',hsk:3,th:['presenter','quotidien']},
  {id:'w312',hz:'关系',py:'guān xi',fr:'relation, lien',hsk:3,th:['presenter','famille']},
  {id:'w313',hz:'认真',py:'rèn zhēn',fr:'sérieux, appliqué',hsk:3,th:['presenter','decrire']},
  {id:'w314',hz:'特别',py:'tè bié',fr:'particulier ; particulièrement',hsk:3,th:['presenter','decrire']},
  {id:'w315',hz:'公司',py:'gōng sī',fr:'entreprise, société',hsk:3,th:['presenter','travail']},
  {id:'w316',hz:'欢迎',py:'huān yíng',fr:'accueillir ; bienvenue',hsk:3,th:['presenter']},
  {id:'w317',hz:'以前',py:'yǐ qián',fr:'avant, autrefois',hsk:3,th:['presenter','temps']},
  {id:'w318',hz:'妻子',py:'qī zi',fr:'épouse',hsk:3,th:['presenter','famille']},

  // ---- HSK 2 · présenter et décrire quelqu’un
  {id:'w221',hz:'男人',py:'nán rén',fr:'un homme',hsk:2,th:['decrire']},
  {id:'w222',hz:'女人',py:'nǚ rén',fr:'une femme',hsk:2,th:['decrire']},
  {id:'w223',hz:'孩子',py:'hái zi',fr:'enfant',hsk:2,th:['decrire','famille']},
  {id:'w224',hz:'眼睛',py:'yǎn jing',fr:'œil, yeux',hsk:2,th:['decrire','sante']},
  {id:'w225',hz:'身体',py:'shēn tǐ',fr:'corps ; santé',hsk:2,th:['decrire','sante']},
  {id:'w226',hz:'高',py:'gāo',fr:'grand (de taille), haut',hsk:2,th:['decrire']},
  {id:'w227',hz:'漂亮',py:'piào liang',fr:'joli, beau',hsk:2,th:['decrire']},
  {id:'w228',hz:'好看',py:'hǎo kàn',fr:'beau, agréable à regarder',hsk:2,th:['decrire']},
  {id:'w229',hz:'白',py:'bái',fr:'blanc',hsk:2,th:['decrire']},
  {id:'w230',hz:'黑',py:'hēi',fr:'noir',hsk:2,th:['decrire']},
  {id:'w231',hz:'快乐',py:'kuài lè',fr:'joyeux, gai',hsk:2,th:['decrire','quotidien']},
  {id:'w232',hz:'忙',py:'máng',fr:'occupé, affairé',hsk:2,th:['decrire','travail']},
  {id:'w233',hz:'累',py:'lèi',fr:'fatigué',hsk:2,th:['decrire','sante']},
  {id:'w234',hz:'穿',py:'chuān',fr:'porter (un vêtement)',hsk:2,th:['decrire','achats']},
  {id:'w235',hz:'衣服',py:'yī fu',fr:'vêtement(s)',hsk:2,th:['decrire','achats']},
  {id:'w236',hz:'觉得',py:'jué de',fr:'trouver, avoir l’impression',hsk:2,th:['decrire','avis']},
  {id:'w237',hz:'非常',py:'fēi cháng',fr:'extrêmement, vraiment très',hsk:2,th:['decrire']},
  {id:'w238',hz:'最',py:'zuì',fr:'le plus (superlatif)',hsk:2,th:['decrire','avis']},

  // ---- HSK 3 · présenter et décrire quelqu’un
  {id:'w321',hz:'头发',py:'tóu fa',fr:'cheveux',hsk:3,th:['decrire']},
  {id:'w322',hz:'聪明',py:'cōng ming',fr:'intelligent',hsk:3,th:['decrire']},
  {id:'w323',hz:'可爱',py:'kě ài',fr:'mignon, adorable',hsk:3,th:['decrire']},
  {id:'w324',hz:'胖',py:'pàng',fr:'gros, corpulent',hsk:3,th:['decrire']},
  {id:'w325',hz:'瘦',py:'shòu',fr:'mince, maigre',hsk:3,th:['decrire']},
  {id:'w326',hz:'矮',py:'ǎi',fr:'petit (de taille)',hsk:3,th:['decrire']},
  {id:'w327',hz:'年轻',py:'nián qīng',fr:'jeune',hsk:3,th:['decrire']},
  {id:'w328',hz:'帅',py:'shuài',fr:'beau (pour un homme)',hsk:3,th:['decrire']},
  {id:'w329',hz:'安静',py:'ān jìng',fr:'calme, silencieux',hsk:3,th:['decrire','logement']},
  {id:'w330',hz:'热情',py:'rè qíng',fr:'chaleureux, accueillant',hsk:3,th:['decrire']},
  {id:'w331',hz:'有名',py:'yǒu míng',fr:'célèbre, renommé',hsk:3,th:['decrire']},
  {id:'w332',hz:'关心',py:'guān xīn',fr:'se soucier de, prendre soin de',hsk:3,th:['decrire','famille']},
  {id:'w333',hz:'性格',py:'xìng gé',fr:'caractère, tempérament',hsk:3,th:['decrire']},
  {id:'w334',hz:'样子',py:'yàng zi',fr:'allure, apparence',hsk:3,th:['decrire']},
  {id:'w335',hz:'眼镜',py:'yǎn jìng',fr:'lunettes',hsk:3,th:['decrire']},
  {id:'w336',hz:'戴',py:'dài',fr:'porter (lunettes, chapeau)',hsk:3,th:['decrire']}
];

const CHARS=[
  {id:'c1',hz:'我',py:'wǒ',fr:'je, moi',hsk:1,th:['presenter']},
  {id:'c2',hz:'叫',py:'jiào',fr:'s\u2019appeler',hsk:2,th:['presenter']},
  {id:'c3',hz:'姓',py:'xìng',fr:'nom de famille',hsk:2,th:['presenter']},
  {id:'c4',hz:'岁',py:'suì',fr:'an(s)',hsk:2,th:['presenter']},
  {id:'c5',hz:'住',py:'zhù',fr:'habiter',hsk:2,th:['presenter']},
  {id:'c6',hz:'介',py:'jiè',fr:'introduire',hsk:3,th:['presenter']},
  {id:'c7',hz:'绍',py:'shào',fr:'relier, présenter',hsk:3,th:['presenter']},
  {id:'c8',hz:'城',py:'chéng',fr:'ville, muraille',hsk:3,th:['presenter','espace']},
  {id:'c9',hz:'高',py:'gāo',fr:'haut, grand',hsk:2,th:['decrire']},
  {id:'c10',hz:'白',py:'bái',fr:'blanc',hsk:2,th:['decrire']},
  {id:'c11',hz:'黑',py:'hēi',fr:'noir',hsk:2,th:['decrire']},
  {id:'c12',hz:'忙',py:'máng',fr:'occupé',hsk:2,th:['decrire','travail']},
  {id:'c13',hz:'胖',py:'pàng',fr:'gros, corpulent',hsk:3,th:['decrire']},
  {id:'c14',hz:'瘦',py:'shòu',fr:'mince, maigre',hsk:3,th:['decrire']},
  {id:'c15',hz:'眼',py:'yǎn',fr:'œil',hsk:3,th:['decrire']},
  {id:'c16',hz:'帅',py:'shuài',fr:'beau, élégant',hsk:3,th:['decrire']}
];
